"""State definition for framework orchestration workflows.

Defines the structure of the shared memory (State) that is passed
sequentially between the Planner, Executor, Strategy, and Validator agents.
"""

from typing import Any, Dict, List, Optional, TypedDict
from pydantic import BaseModel, Field


class TraceStep(BaseModel):
    """Represents a single step in the agent execution timeline."""
    node: str = Field(..., description="The name of the workflow node that executed (e.g. 'planner', 'executor').")
    action: str = Field(..., description="Description of the action taken.")
    timestamp: str = Field(..., description="ISO 8601 timestamp of execution.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context about this execution step.")


class Task(BaseModel):
    """Represents an independent logical task in the execution plan."""
    id: str = Field(..., description="Unique task identifier (e.g. 'task_1', 'task_2').")
    title: str = Field(..., description="Short title of the task.")
    sub_query: str = Field(..., description="A specific sub-query or goal to execute for this task.")
    priority: int = Field(default=1, description="Execution priority (lower is higher priority).")
    status: str = Field(default="pending", description="Task status (pending, running, completed, failed).")
    depends_on: List[str] = Field(default_factory=list, description="IDs of tasks that must complete before this task executes.")
    required_context: List[str] = Field(default_factory=list, description="Keys of context variables expected to be present.")
    expected_output: str = Field(..., description="Description of the expected result output.")
    result: Optional[str] = Field(default=None, description="The stringified results or error details collected for this task.")


class ExecutionPlan(BaseModel):
    """The structured task decomposition plan generated by the Query Planner."""
    goal: str = Field(..., description="The overall goal synthesized from the user request.")
    planner_reasoning: str = Field(..., description="Explanation of why this specific decomposition plan was created.")
    tasks: List[Task] = Field(..., description="List of tasks in the execution plan.")


class AgentState(TypedDict):
    """The complete shared state passed between nodes in the framework execution graph."""
    
    # Input query from the user
    query: str
    
    # Conversational memory context (e.g. Chat history, variables)
    conversation_history: List[Dict[str, Any]]
    
    # Aggregated system context (e.g. parameters, active files, configurations)
    context: Dict[str, Any]
    
    # Registered tool metadata schemas available for the planner to review
    available_tools: List[Dict[str, Any]]
    
    # List of tool names selected by the planner agent
    selected_tools: List[str]
    
    # Dictionary mapping tool names to their raw outputs
    tool_outputs: Dict[str, Any]
    
    # The final strategic recommendation text compiled by the Strategy Agent
    recommendation: Optional[str]
    
    # Validation results from the Validator Agent check (e.g. status, warnings, errors)
    validation: Optional[Dict[str, Any]]
    
    # Detailed execution steps tracing the performance and actions of the orchestrator
    execution_trace: List[Dict[str, Any]]
    
    # Multi-turn conversation contents for Gemini function-calling loops
    contents: List[Any]
    
    # Custom extensible metadata dictionary for tracking sessions, requests, etc.
    metadata: Dict[str, Any]

    # Route decision (planning or general)
    route_decision: Optional[str]

    # Query Planning & Execution Plan variables
    execution_plan: Optional[Dict[str, Any]]
    current_task: Optional[str]
    completed_tasks: List[str]
    failed_tasks: List[str]
    task_results: Dict[str, Any]
    planner_reasoning: Optional[str]
    planner_metadata: Dict[str, Any]

    # Per-query diagnostics data (timings, LLM call counts, node durations)
    diagnostics: Dict[str, Any]


def create_initial_state(query: str, history: Optional[List[Dict[str, Any]]] = None) -> AgentState:
    """Helper factory to instantiate an empty, clean initial workflow state.

    Args:
        query: The user's input query.
        history: Optional conversation history.
    """
    return {
        "query": query,
        "conversation_history": history or [],
        "context": {},
        "available_tools": [],
        "selected_tools": [],
        "tool_outputs": {},
        "recommendation": None,
        "validation": None,
        "execution_trace": [],
        "contents": [],
        "metadata": {},
        "route_decision": None,
        "execution_plan": None,
        "current_task": None,
        "completed_tasks": [],
        "failed_tasks": [],
        "task_results": {},
        "planner_reasoning": None,
        "planner_metadata": {},
        "diagnostics": {
            "query_start_time": None,
            "query_end_time": None,
            "total_duration_s": None,
            "node_timings": [],
            "llm_calls": [],
            "embedding_calls": [],
            "tool_executions": [],
        }
    }
